version: '3.9'

services:
  spark-master:
    image: apache/spark
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8888:8080"
    networks:
      - spark-network
    volumes:
      - /opt/java
      - /opt/spark
  spark-worker:
    image: apache/spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - spark-network
    volumes:
      - ./worker_data:/opt/spark/work
  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - 1111:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "danil_the_best"
      JAVA_HOME: "/opt/java/openjdk"
      JAVA_VERSION: "11.0.20.1"
      SPARK_HOME: "/opt/spark"
    volumes:
      - ./notebook:/home/jovyan/notebook
    volumes_from:
      - spark-master:rw
    networks:
      - spark-network
networks:
  spark-network:


